version: 2.22.0

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mp3player
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mp3player
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  postgres_data:
